version: '3'
services:

  postgres:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "sos_admin"
      POSTGRES_PASSWORD: "kZpmbT9dqqmsJHo8bshZ"
      POSTGRES_DB: "t_sos_p"
